### PR TITLE
Update Docker Environment to Resolve Module Bugs

### LINKED ISSUE #105: Proposed Analysis: Explore updating JASPAR
## What are the scientific goals of the analysis?

We will explore updating the JASPAR version in the `motif-footprint-analysis` module for compatibility with CellRanger based on the build steps in their [documentation](https://www.10xgenomics.com/support/software/cell-ranger-arc/downloads/ref-build-steps). This was suggested by @sharonfreshour [here](https://github.com/stjude-dnb-binfcore/sc-epigenie/pull/92).

## Reference Genome & Pipeline Integration

- CellRanger 2020 references use JASPAR2018.
- CellRanger 2024 references use JASPAR2024.
- Our code currently loads JASPAR2020 by default.

## Background Distributions and Metadata Improvements
Each release improves:

- GC-content adjusted background models
- TF class annotations
- Matrix quality scores
- Links to UniProt, TFClass, and literature

2024 has the most complete metadata.

### JASPAR Release Comparison

| Feature                     | JASPAR2018 | JASPAR2020 | JASPAR2024 |
|----------------------------|------------|------------|------------|
| **Vertebrate motifs**      | ~579       | ~745       | ~950+      |
| **New data types included**| Mostly ChIP‑seq | + SELEX, DAP‑seq | Much‑expanded DAP‑seq + orthologs |
| **Matrix updates**         | Moderate   | Significant | Largest update cycle so far |
| **TF diversity**           | Limited    | Broader     | Broadest & most curated |
| **Pipeline usage (Cell Ranger)\*** | Used in 2020 references | — | Used in 2024 references |

\*Pipeline usage based on internal team note regarding Cell Ranger reference builds.

## Next steps

Even though CellRanger 2020 used JASPAR2018, many internal tools written between 2020–2023 assumed:

- JASPAR2020 had broader vertebrate coverage
- Better support for downstream motif enrichment tools
- A stable ID structure

When the downstream pipeline (chromVAR, Signac, ArchR wrappers) expects 2020-era motifs, choosing JASPAR2020 will be best. 

- [ ] To test if JASPAR2024 is compatible with running the `motif-footprint-analysis` module.
- [ ] To test if JASPAR2018 is compatible with running the `motif-footprint-analysis` module.
- [ ] To test if JASPAR can be a variable or it will be hardcoded.
- [ ] To test if multiple versions of JASPAR can be installed in the container.

### LINKED ISSUE #106: Bug: FetchData() error with SeuratObject v5
## What analysis module should be updated and why?
I ran in to following  issue in `upstream-analysis` module that roots from `01A_run_signac_qc.Rmd` due to SeuratObject version conflict.

```
Error:
! The `slot` argument of `FetchData()` was deprecated in SeuratObject
  5.0.0 and is now defunct.
i Please use the `layer` argument instead.
Backtrace:
    x
 1. \-Seurat::VlnPlot(...)
 2.   \-Seurat:::ExIPlot(...)
 3.     +-SeuratObject::FetchData(object = object, vars = features, slot = slot)
 4.     \-SeuratObject:::FetchData.Seurat(...)
 5.       \-SeuratObject::.Deprecate(...)
 6.         \-lifecycle::deprecate_stop(...)
 7.           \-lifecycle:::deprecate_stop0(msg)
 8.             \-rlang::cnd_signal(...)
Warning message:
In read.table(file = file, header = header, sep = sep, quote = quote,  :
  incomplete final line found by readTableHeader on '/sc-epigenie-test-multiome-data/data/project_metadata/project_metadata.tsv'

Quitting from 01A_run_signac_qc.Rmd:406-415 [vln-plot-before-filtering-1]
Execution halted
```

**Reason:**
Loading `SeuratObject` directly from CRAN is downloading most recent version i.e 5.0.0 which is not compatible with the pipeline that is set up on Seurat/SeuratObject v4.

## What changes need to be made? Please provide enough detail for another participant to make the update.

Below workaround worked in another analysis that is run outside of the container. This may troubleshoot the issue we are seeing. It is worth a try!

Loading the packages in the specified order:
1. `library(SeuratObject)` # Downloaded from CRAN, loads 5.0.0 version.
2. `library(Signac)`
3. `remove.packages("SeuratObject")`
4. `remotes::[install_version](https://remotes.r-lib.org/reference/install_version.html)("SeuratObject", "4.1.4", repos = [c](https://rdrr.io/r/base/c.html)("https://satijalab.r-universe.dev", [getOption](https://rdrr.io/r/base/options.html)("repos")))`
[Link to loading older versions of Seurat/SeuratObject](https://satijalab.org/seurat/articles/install_v5.html)

## What input data and from which project should be used? 
Testing `sc-epigenie` on THRB2-10x-multiome data - [stjude-dnb-binfcore/sc-epigenie-test-multiome-data](https://github.com/stjude-dnb-binfcore/sc-epigenie-test-multiome-data)

### LINKED ISSUE #110: Bug: vln plots in the `01A_run_signac_qc.Rmd` script
## What analysis module should be updated and why?

There is a bug in the `FetchData()` function, which was deprecated in SeuratObject (introduced after the container was updated). This time affects the generation of vln plots in the `01A_run_signac_qc.Rmd` script of the `upstream-analysis` module. This issue was reported here: https://github.com/stjude-dnb-binfcore/sc-epigenie/issues/106.

- [x] To create a function to manually create vln plots and update the code accordingly in the  `01A_run_signac_qc.Rmd` script.
- [x] Test by using the testing cohort -> Run **only script 1**.

### LINKED ISSUE #113: Bug: `PackageCheck()` deprecated in SeuratObject 5.0.0 in the `02_run_scDblFinder.Rmd`
## What analysis module should be updated and why?

There is a similar bug coming up in the `02_run_scDblFinder.Rmd` in the `upstream-analysis` module. For more details, see:

```
Error:
! `PackageCheck()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use `rlang::check_installed()` instead.
Backtrace:
    x
 1. +-Seurat::as.SingleCellExperiment(sce_obj_list[[i]])
 2. \-Seurat:::as.SingleCellExperiment.Seurat(sce_obj_list[[i]])
 3.   \-SeuratObject::PackageCheck("SingleCellExperiment", error = FALSE)
 4.     \-SeuratObject::.Deprecate(...)
 5.       \-lifecycle::deprecate_stop(...)
 6.         \-lifecycle:::deprecate_stop0(msg)
 7.           \-rlang::cnd_signal(...)

Quitting from 02_run_scDblFinder.Rmd:215-350 [run-recoverDoublets-plot-predictions]
```

I will be creating a function to bypass this issue.

### LINKED ISSUE #115: Bug: `PackageCheck()` deprecated in SeuratObject 5.0.0 in the ` 01-building-trajectories-monocle.Rmd`
## What analysis module should be updated and why?

Bug with `PackageCheck()` being deprecated in SeuratObject 5.0.0 in the ` 01-building-trajectories-monocle.Rmd` of the `building-trajectories-monocle` module.

```
processing file: 01-building-trajectories-monocle.Rmd
  |.............................             |  70% [trajectories-each-lineage]

Error:
! `PackageCheck()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use `rlang::check_installed()` instead.
Backtrace:
     x
  1. \-global predict_trajectories(...)
  2.   +-global as.cell_data_set(seurat_obj)
  3.   \-global as.cell_data_set.Seurat(seurat_obj)
  4.     +-methods::as(...)
  5.     | \-methods:::.class1(object)
  6.     +-Seurat::as.SingleCellExperiment(x = x, assay = assay)
  7.     \-Seurat:::as.SingleCellExperiment.Seurat(x = x, assay = assay)
  8.       \-SeuratObject::PackageCheck("SingleCellExperiment", error = FALSE)
  9.         \-SeuratObject::.Deprecate(...)
 10.           \-lifecycle::deprecate_stop(...)
 11.             \-lifecycle:::deprecate_stop0(msg)
 12.               \-rlang::cnd_signal(...)

Quitting from 01-building-trajectories-monocle.Rmd:247-377 [trajectories-each-lineage]
```

### LINKED ISSUE #116: Bug: FetchData() deprecated in SeuratObject 5.0.0 in the `01-integrative-analysis.Rmd`
## What are the scientific goals of the analysis?

There is a bug coming up in the `01-integrative-analysis.Rmd` in the `integrative-analysis` module. For more details, see:

```
Error:
! The `slot` argument of `FetchData()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use the `layer` argument instead.
Backtrace:
    x
 1. \-Seurat::VlnPlot(...)
 2.   \-Seurat:::ExIPlot(...)
 3.     +-SeuratObject::FetchData(object = object, vars = features, slot = slot)
 4.     \-SeuratObject:::FetchData.Seurat(...)
 5.       \-SeuratObject::.Deprecate(...)
 6.         \-lifecycle::deprecate_stop(...)
 7.           \-lifecycle:::deprecate_stop0(msg)
 8.             \-rlang::cnd_signal(...)

Quitting from 01-integrative-analysis.Rmd:214-232 [use-harmony-integration]
                                                                                                                           
Execution halted
```

### LINKED ISSUE #117: Bug: GetAssayData() and PackageCheck() deprecated in SeuratObject 5.0.0 in the `integration-with-scrna-seq-data` module
## What analysis module should be updated and why?

There are the following bugs in the `integration-with-scrna-seq-data` module:

1. Bug in the `01-integration-with-scrna-seq-data.Rmd` script:

```
Error:
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use the `layer` argument instead.
Backtrace:
     x
  1. +-Seurat::FindVariableFeatures(object = atac_query, nfeatures = nfeatures_value)
  2. \-Seurat:::FindVariableFeatures.Seurat(object = atac_query, nfeatures = nfeatures_value)
  3.   +-Seurat::FindVariableFeatures(...)
  4.   \-Seurat:::FindVariableFeatures.Assay(...)
  5.     +-SeuratObject::GetAssayData(object = object, slot = "counts")
  6.     \-SeuratObject:::GetAssayData.Assay(object = object, slot = "counts")
  7.       \-SeuratObject::.Deprecate(...)
  8.         \-lifecycle::deprecate_stop(...)
  9.           \-lifecycle:::deprecate_stop0(msg)
 10.             \-rlang::cnd_signal(...)

Quitting from 01-integration-with-scrna-seq-data.Rmd:206-210 [read-object]
                                                                                                                                 
Execution halted
```

2. Bug in the `02-peak-calling.Rmd` script:

```
Error:
! The `slot` argument of `GetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use the `layer` argument instead.
Backtrace:
    x
 1. \-Seurat::DoHeatmap(seurat_obj, features = top_peaks)
 2.   +-base::rownames(x = GetAssayData(object = object, slot = slot))
 3.   | \-dimnames(x)[[1L]] %||% ...
 4.   +-SeuratObject::GetAssayData(object = object, slot = slot)
 5.   \-SeuratObject:::GetAssayData.Seurat(object = object, slot = slot)
 6.     \-SeuratObject::.Deprecate(...)
 7.       \-lifecycle::deprecate_stop(...)
 8.         \-lifecycle:::deprecate_stop0(msg)
 9.           \-rlang::cnd_signal(...)

Quitting from 02-peak-calling.Rmd:309-318 [plot-peaks]
                                                                                                                                   
Execution halted
```

3. Bug in the `03-finding-co-accessible-networks-cicero.Rmd` script:

```
Error:
! `PackageCheck()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use `rlang::check_installed()` instead.
Backtrace:
     x
  1. +-global as.cell_data_set(x = seurat_obj)
  2. \-global as.cell_data_set.Seurat(x = seurat_obj)
  3.   +-methods::as(...)
  4.   | \-methods:::.class1(object)
  5.   +-Seurat::as.SingleCellExperiment(x = x, assay = assay)
  6.   \-Seurat:::as.SingleCellExperiment.Seurat(x = x, assay = assay)
  7.     \-SeuratObject::PackageCheck("SingleCellExperiment", error = FALSE)
  8.       \-SeuratObject::.Deprecate(...)
  9.         \-lifecycle::deprecate_stop(...)
 10.           \-lifecycle:::deprecate_stop0(msg)
 11.             \-rlang::cnd_signal(...)

Quitting from 03-finding-co-accessible-networks-cicero.Rmd:256-273 [create-cds-object]
```

### LINKED ISSUE #118: Bug: `SetAssayData()` deprecated in SeuratObject 5.0.0  in the `cluster-cell-calling` module
## What analysis module should be updated and why?

There are the following bugs in the `cluster-cell-calling` module:

1. Bug in the `02-create-gene-activity-matrix.Rmd` script:

```
processing file: 02-create-gene-activity-matrix.Rmd
  |...................               |  56% [normalize-matrix]                 

Error:
! The `slot` argument of `SetAssayData()` was deprecated in SeuratObject 5.0.0 and is now defunct.
i Please use the `layer` argument instead.
Backtrace:
     x
  1. +-Seurat::NormalizeData(...)
  2. \-Seurat:::NormalizeData.Seurat(...)
  3.   +-Seurat::NormalizeData(...)
  4.   \-Seurat:::NormalizeData.Assay(...)
  5.     +-SeuratObject::SetAssayData(...)
  6.     \-SeuratObject:::SetAssayData.Assay(...)
  7.       \-SeuratObject::.Deprecate(...)
  8.         \-lifecycle::deprecate_stop(...)
  9.           \-lifecycle:::deprecate_stop0(msg)
 10.             \-rlang::cnd_signal(...)

Quitting from 02-create-gene-activity-matrix.Rmd:328-339 [normalize-matrix]
                                                                                                                              
Execution halted
```

2. Bug in the `03-find-peaks.Rmd` script, Lines 267-278:

```
Warning: No DE genes identified
Warning: The following tests were not performed:
Warning: When testing 1 versus all:
        `PackageCheck()` was deprecated in SeuratObject 5.0.0 and is now defunct.Please use `rlang::check_installed()` instead.
```

### LINKED ISSUE #120: Bug: Update Docker Environment to Resolve Module Bugs
## What analysis module should be updated and why?

A series of bugs have been reported that are all linked to changes introduced by updates on the container:
#118, #117, #116, #115, #113, #110, and #106.

To investigate, I compared and tested the following Docker images:

- `achronistjude/singlecell-r4.4-seurat4.4-signac1.16-2025-oct:latest`: Signac 1.16.0; SeuratWrappers_0.2.0; SeuratObject_5.2.0; Seurat_4.4.0  
- `achronistjude/singlecell-r4.4-seurat4.4-signac1.16-2025-12-24:latest`:  Signac 1.16.9004 (development build); SeuratWrappers_0.2.0; SeuratObject_5.3.0; Seurat_4.4.0  

The second image was also updated to include additional R packages required for the `motif-footprint-analysis` module:

- `BSgenome.Mmusculus.UCSC.mm39`
- `chromVAR`
- `ggseqlogo`

However, using `Signac 1.16.9004` instead of `1.16.0` and/or `SeuratObject_5.3.0` instead of `SeuratObject_5.2.0` caused several incompatibilities, leading to the bugs listed above.

## What changes need to be made? Please provide enough detail for another participant to make the update.

To resolve the issues:

- [x] I updated the Dockerfile to explicitly install `Signac 1.16.0` and `SeuratObject_5.2.0` (stable release).
- [x] I added supporting R packages needed for the footprinting module and referenced in issue #105:
     - JASPAR2018
     - JASPAR2022
     - JASPAR2024

### How to test

From the feature branch (root directory):

```
singularity pull docker://achronistjude/singlecell-r4.4-seurat4.4-signac1.16-2026-02-03-v2:latest
```

Then rename the image:

```
mv singlecell-r4.4-seurat4.4-signac1.16-2026-02-03-v2_latest.sif \
   singlecell-r4.4-seurat4.4-signac1.16-latest.sif
```

## What input data and from which project should be used? 

- Updates were validated using data from: https://github.com/stjude-dnb-binfcore/sc-epigenie-Victoria-Knockout/tree/main

### LINKED ISSUE #122: Proposed Analysis: Script to launch full pipeline
## What are the scientific goals of the analysis?

This analysis requires running the full sc‑epigenie workflow using the script `launch_sc_epigenie_full_pipeline.sh`.

This script orchestrates all stages of the sc‑epigenie pipeline in the correct order and ensures reproducible, container‑based execution. It also allows every module to be toggled on or off, enabling flexible reruns while preserving full workflow structure.

The script should be executed from an interactive node in the project’s root_dir:

```
bash launch_sc_epigenie_full_pipeline.sh
```

## Why this script is needed

The full sc‑epigenie workflow consists of multiple dependent modules (QC, upstream analysis, integration, cluster calling, trajectory inference, motif analysis, etc.). Running these modules manually is error‑prone because:

- Each module depends on the successful completion of specific upstream steps.
- Some steps may be optionally skipped depending on which results already exist.
- The order of execution must be preserved to maintain scientific validity.
- Different modules rely on the same container environment, which must be validated before the run.
- Re‑running modules without clearing previous results can contaminate downstream analyses.

`launch_sc_epigenie_full_pipeline.sh` solves these problems by:

- Submitting each module as an LSF job in the correct order
- Automatically wiring dependencies between enabled steps
- Allowing optional execution of any module (via RUN_* flags)
- Ensuring reproducibility and consistent container usage
- Providing email notifications on job completion or failure

This makes the pipeline robust, reproducible, and safe to run across large datasets. This also facilitates testing/validation phases during pipeline development and maintenance.

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## What scientific question/module of analysis is your analysis addressing?

This PR addresses the issue described in #https://github.com/stjude-dnb-binfcore/sc-epigenie/issues/120. It also fixes and closes a series of GitHub issues as described below.

## What GitHub issue does your pull request address?

Closes #105.
Closes #106.
Closes #110.
Closes #113.
Closes #115.
Closes #116.
Closes #117.
Closes #118.
Closes #120.
Closes #122.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

### Which areas should receive a particularly close look?

1. `run-container` folder:

- [x] Please review the code for logic and documentation.
- [x] Run via LSF to test successful installation of new packages.
- [x]  Run via interactive node to test successful installation of new packages.

2. Run `launch_sc_epigenie_full_pipeline.sh` as described in the `./README.md` file.

This script runs all sc‑epigenie modules sequentially except cellranger-analysis. Before running it, please ensure the following:

- `cellranger-analysis` must already contain completed alignment outputs. If alignment has not been performed, run the CellRanger module as well (by selecting in the file: `RUN_CELLRANGER=1`).
- All other module directories should contain only code, not previously generated plots/ or results/ folders. Remove or relocate old outputs to avoid conflicts or accidental reuse.
- Verify that your container/environment executes correctly and that no errors or missing dependencies are reported when launching any of the module scripts.

## Reproducibility Checklist

- [x] The dependencies required to run the code in this pull request have been added to the project Dockerfile.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

File: launch_sc_epigenie_full_pipeline.sh
Comment (sharonfreshour) [inline launch_sc_epigenie_full_pipeline.sh]: Based on the documentation within the script, it suggests that this script should be able to run the `cellranger` module as part of the full pipeline launch. However, toggling the `cellranger` step on in the script causes the downstream modules to fail, specifically because the `upstream-analysis` module launches too early and fails (and in turn the remaining modules are not launched). This is because the dependent job for launching the `upstream-analysis` job is the job ID for the `sumbit-multiple-jobs.sh` job of the `cellranger` module. However, the `sumbit-multiple-jobs.sh` job completing successfully only indicates that all the `cellranger` alignment jobs have been submitted successfully, not completed successfully. These alignments completing succesfully should be the actual dependency for the `upstream-analysis` module job to be launched. I have not explored any possible solutions to this yet, though.

If the `cellranger` module should be run separately and the results should exist prior to running this launch script for the other modules, that should be made clearer in the documentation.

File: launch_sc_epigenie_full_pipeline.sh [hunk 1]
```diff
@@ -0,0 +1,336 @@
...
+#   1) Edit the configuration section near the top:
+#        - NOTIFY_EMAIL="antonia.chroni@stjude.org"
+#        - NOTIFY_ON_START=0|1
+#        - RUN_FASTQC / RUN_CELLRANGER / ... / RUN_RSHINY = 0|1
+#        - CELLRANGER_WAIT_FOR_FASTQC=0|1
+#   2) Ensure each module directory has its LSF script:
+#        analyses/<module>/lsf-script.txt
+#        (CellRanger may use submit-multiple-jobs.sh to fan out internal jobs.)
+#   3) Run from anywhere:
+#        bash launch_sc_epigenie.sh
```
Comment (sharonfreshour) [inline launch_sc_epigenie_full_pipeline.sh]: I think this needs to be updated to reflect the current name of the launch script, i.e.


```suggestion
#        bash launch_sc_epigenie_full_pipeline.sh
```

**Review by sharonfreshour — COMMENTED** [review]
The `run-container` tests for both interactive and LSF runs complete successfully and show that the appropriate package versions for `Signac` (v1.1.6.0) and `SeuratObject` (v5.2.0) are installed.

All modules run successfully and do not display any errors related to missing packages or package versions.

However, there is a bug related to the `cellranger` and `upstream-analysis` steps being submitted with the `launch_sc_epigenie_full_pipeline.sh` script. I left more detailed comments on the script itself.

Otherwise, the `launch_sc_epigenie_full_pipeline.sh` successfully runs all other modules, including the `upstream-analysis` module, if `cellranger` results are available prior to running the launch script.

File: launch_sc_epigenie_full_pipeline.sh [hunk 2]
```diff
@@ -0,0 +1,384 @@
...
+
+cd "$(dirname "${BASH_SOURCE[0]}")"
+PROJECT_DIR="$(pwd)"
+
+# ------------------------------------------------------------------------------
+# Notifications
+# ------------------------------------------------------------------------------
+# All jobs will notify on completion (-N) to this email.
+# Set NOTIFY_ON_START=1 to also get a mail when a job starts (-B).
+NOTIFY_EMAIL="antonia.chroni@stjude.org"
```
Comment (sharonfreshour) [inline launch_sc_epigenie_full_pipeline.sh]: You might consider replacing this with some sort of placeholder email address, so if users forget to change it, you aren't accidentally getting emails for other users' pipeline runs. E.g.


```suggestion
NOTIFY_EMAIL="user.name@stjude.org"
```

**Review by sharonfreshour — APPROVED** [review]
The code appears to be clear and logical and the `launch_sc_epigenie_full_pipeline.sh` script now successfully launches all modules sequentially, including the `cellranger` and `upstream-analysis` modules.

I did note that the `cellranger` step no longer generates launch/completion emails, but it does not impact the functionality of the `cellranger` step. I left more detailed comments on the script.

Also, just a reminder, make sure that updates to the `motif-footprint-analysis` module for using the `motifs_to_fp_module_list_value` variable for the `footprinting` step are incorporated when merging to the main branch. In this testing branch, it appears that the `02-motif-footprinting-analysis.Rmd` script has been updated, but the `yaml` file, `run-motif-footprint-analysis.R`, script and `util/function-add-footprinting.R` script are not updated to reflect the current state of the main branch.

Otherwise, looks good! Approved.

File: launch_sc_epigenie_full_pipeline.sh [hunk 3]
```diff
@@ -0,0 +1,384 @@
...
+#   • Optional per-step execution via RUN_* flags.
+#   • Adaptive dependencies: each enabled step depends on the last enabled predecessor.
+#   • Configurable relationship between FastQC and CellRanger:
+#       - CELLRANGER_WAIT_FOR_FASTQC=1 → B waits for A (done(A))
+#       - CELLRANGER_WAIT_FOR_FASTQC=0 → A and B run in parallel
+#   • LSF email notifications with a single NOTIFY_EMAIL value for all jobs.
+#
+# Usage:
+#   1) Edit the configuration section near the top:
+#        - NOTIFY_EMAIL="antonia.chroni@stjude.org"
```
[the remark this answers is not in the document]
Comment (AntoniaChroni) [reply launch_sc_epigenie_full_pipeline.sh]: Thanks for noticing! See f33b1dd78536b1e76c0c07c97e404a19ea9eb9a4.

File: launch_sc_epigenie_full_pipeline.sh [hunk 4]
```diff
@@ -0,0 +1,373 @@
...
+# Script:        launch_sc_epigenie_full_pipeline.sh
+# Purpose:       Launch the full sc-epigenie pipeline on LSF as a dependency-
+#                aware job chain, with fully OPTIONAL steps and adaptive waits.
+#
+# Summary:
+#   - Submits the end-to-end sc-epigenie workflow (A→I) to LSF.
+#   - Every step can be toggled on/off independently.
+#   - Dependencies automatically wire up only between ENABLED steps.
+#   - CellRanger can run in parallel with FastQC or wait for it, based on a flag.
+#   - Email notifications sent on completion (and optionally on start) of each job.
```
[the remark this answers is not in the document]
Comment (AntoniaChroni) [reply launch_sc_epigenie_full_pipeline.sh]: That is a great idea ~ updated in the script and `README.md` file, see 1033ffb3423bb6ea322e97c0741c8595d298f182.
